#!/bin/sh

echo "# Generated by $0" > /etc/apache2/rewrite-env-rules.conf

printenv | grep '^REWRITE_' | sort -fibn -t'_' -k2 | while read -r rule; do
    set -f
    ruleid=$(echo $rule | cut -f1 -d'=')
    rule=$(echo $rule | cut -f2- -d'=')
    src=$(echo $rule | cut -s -f2- -d' ')
    dst=$(echo $rule | cut -s -f1 -d' ')

    if [ -z "$src" ] || [ -z "$dst" ]; then continue; fi

    if [ $ENABLE_JSON_LOG == "1" ] || [ "$ENABLE_JSON_LOG" == "true" ] || [ "$ENABLE_JSON_LOG" == "on" ]; then
        echo "{\"type\":\"info\",\"time\":\"$(date +'%F %T.%s' | cut -c-26)\",\"sender\":\"rewrite_proxy\",\"from\":\"$src\",\"to\":\"$dst\"}"
    else
        echo "[$(date +'%F %T.%s' | cut -c-26)] -:rewrite_proxy:${ruleid##*_} $src -> $dst"
    fi

    echo "
    # ${ruleid##*_} TO: $dst FROM: $src" >> /etc/apache2/rewrite-env-rules.conf
    if [[ $dst =~ '^\w+://.+' ]]; then
        # Handle custom protocol
        echo "
        RewriteCond %{HTTP_HOST} \"^$src(?::\d+)?\$\" [NC]
        RewriteRule .* \"$dst%{REQUEST_URI}\" [P,QSA,NS,L]" >> /etc/apache2/rewrite-env-rules.conf
    else
        # Handle http/ws by default
        echo "
        RewriteCond %{HTTP:Connection} Upgrade [NC]
        RewriteCond %{HTTP:Upgrade} websocket [NC]
        RewriteCond %{HTTP_HOST} \"^$src(?::\d+)?\$\" [NC]
        RewriteRule .* \"ws://$dst%{REQUEST_URI}\" [P,QSA,NS,L]
        RewriteCond %{HTTP_HOST} \"^$src(?::\d+)?\$\" [NC]
        RewriteRule .* \"http://$dst%{REQUEST_URI}\" [P,QSA,NS,L]" >> /etc/apache2/rewrite-env-rules.conf
    fi
done

gateway=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')
if [ -n "$gateway" ]; then
    export TRUSTED_PROXIES="$TRUSTED_PROXIES $gateway"
fi

if [ -n "$SERVER_STATUS_ENDPOINT" ]; then
    HTTPD_ARGS="$HTTPD_ARGS -DSERVER_STATUS_ENDPOINT"
fi

if [ -n "$SERVER_INFO_ENDPOINT" ]; then
    HTTPD_ARGS="$HTTPD_ARGS -DSERVER_INFO_ENDPOINT"
fi

if [ "$ENABLE_DEFLATE" == "1" ] || [ "$ENABLE_DEFLATE" == "true" ] || [ "$ENABLE_DEFLATE" == "on" ]; then
    HTTPD_ARGS="$HTTPD_ARGS -DENABLE_DEFLATE"
fi

if [ "$ACME_DOMAINS" != "" ] && ( [ "$ENABLE_ACME" == "1" ] || [ "$ENABLE_ACME" == "true" ] || [ "$ENABLE_ACME" == "on" ] ); then
    HTTPD_ARGS="$HTTPD_ARGS -DENABLE_ACME"
fi

if [ "$ENABLE_HTTP2" == "1" ] || [ "$ENABLE_HTTP2" == "true" ] || [ "$ENABLE_HTTP2" == "on" ]; then
    HTTPD_ARGS="$HTTPD_ARGS -DENABLE_HTTP2"
fi

if [ "$ENABLE_JSON_LOG" == "1" ] || [ "$ENABLE_JSON_LOG" == "true" ] || [ "$ENABLE_JSON_LOG" == "on" ]; then
    HTTPD_ARGS="$HTTPD_ARGS -DENABLE_JSON_LOG"
fi

rm -f /usr/local/apache2/logs/httpd.pid
exec httpd -DFOREGROUND -T $HTTPD_ARGS -f /etc/apache2/httpd.conf
